<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Harshas-Macbook-Air.local" failures="2" tests="2" name="EdgeTest" time="68.199" errors="0" timestamp="2025-10-30T21:59:38 IST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verify_AccountRegistration" time="20.179">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at testCases.TC001_AccountRegistrationTest.verify_AccountRegistration(TC001_AccountRegistrationTest.java:54)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verify_AccountRegistration -->
  <testcase classname="testCases.TC002_LoginTest" name="verify_Login" time="20.133">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC002_LoginTest.verify_Login(TC002_LoginTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verify_Login -->
</testsuite> <!-- EdgeTest -->
